# Numpy Exercises 2

In [1]:
import numpy as np

import matplotlib.pyplot as plt
import random # Thư viện built-in của Python 

**Question 1**

Search for the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as `True`. First time occurrences should be `False` \
Input: `[0 0 3 0 2 4 2 2 2 2]` \
Correct Output: `[False  True False  True False False  True  True  True  True]`

In [2]:
#Init array
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#TODO
# get unique value from array
val, i = np.unique(a, return_index=True)
# check duplicate
dups = np.zeros_like(a, dtype=bool)
dups[i] = True
dups = dups != True
print(dups)

Array:  [0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]


**Question 2**

Return all items in array `a` that not in array `b` \
Input: \
`a` = `[1,2,3,4,5]` \
`b` = `[5,6,7,8,9]` \
Output: \
`[1,2,3,4]`

In [11]:
a = np.random.choice(range(10), 7, replace=False)
b = np.random.choice(range(10), 7, replace=False)
print(a,b)
#TODO
# get elements in a array not in b array
res = list(set(a) - set(b))
res

[9 4 2 7 1 0 6] [5 9 0 1 8 7 2]


[1, 2, 3, 4]

**Question 3**

Given a vector `a`, build a new vector with 2 consecutive zeros interleaved between each value. \
Input: \
`a` = `[4, 3, 4, 9, 8]` \
Output: \
`[4. 0. 0. 3. 0. 0. 4. 0. 0. 9. 0. 0. 8.]`

In [4]:
a = np.random.randint(1, 10, 5)
a = [4, 3, 4, 9, 8]
#TODO
new_nums = np.zeros(len(a) + (len(a)-1)*2)
new_nums[::3] = a
new_nums

array([4., 0., 0., 3., 0., 0., 4., 0., 0., 9., 0., 0., 8.])

---
*For the next few questions we will work with `Iris Dataset`*

In [5]:
iris_2d = np.genfromtxt('Data/Iris.csv', delimiter=',', dtype='float', 
                        skip_header=1, usecols=[0,1,2,3])
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

**Question 4**\
Filter the rows of iris_2d that has `petallength` (3rd column) > 1.5 and `sepallength` (1st column) < 5.0

In [6]:
#TODO
fil_array = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.)

newarr = iris_2d[fil_array]
newarr

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

**Question 5**\
Add a new text column to `iris_2d`, which based on the petal length (3rd) column, such that if petal length is: \
- `Less than 3` --> 'small'
- `3-5` --> 'medium'
- `>=5` --> 'large'

In [7]:
#TODO
# get petal length in 2nd column
petal_len = iris_2d[:, 2]
# create empty list contain size
text_col = []
# check conditions
for i in petal_len:
    if i < 3:
        text_col.append('small')
    elif i >= 3 and i < 5:
        text_col.append('medium')
    elif i >= 5:
        text_col.append('large')
text_arr = np.array(text_col)
text_arr = np.atleast_2d(text_arr).T
np.append(iris_2d, text_arr, axis=1)

array([['5.1', '3.5', '1.4', '0.2', 'small'],
       ['4.9', '3.0', '1.4', '0.2', 'small'],
       ['4.7', '3.2', '1.3', '0.2', 'small'],
       ['4.6', '3.1', '1.5', '0.2', 'small'],
       ['5.0', '3.6', '1.4', '0.2', 'small'],
       ['5.4', '3.9', '1.7', '0.4', 'small'],
       ['4.6', '3.4', '1.4', '0.3', 'small'],
       ['5.0', '3.4', '1.5', '0.2', 'small'],
       ['4.4', '2.9', '1.4', '0.2', 'small'],
       ['4.9', '3.1', '1.5', '0.1', 'small'],
       ['5.4', '3.7', '1.5', '0.2', 'small'],
       ['4.8', '3.4', '1.6', '0.2', 'small'],
       ['4.8', '3.0', '1.4', '0.1', 'small'],
       ['4.3', '3.0', '1.1', '0.1', 'small'],
       ['5.8', '4.0', '1.2', '0.2', 'small'],
       ['5.7', '4.4', '1.5', '0.4', 'small'],
       ['5.4', '3.9', '1.3', '0.4', 'small'],
       ['5.1', '3.5', '1.4', '0.3', 'small'],
       ['5.7', '3.8', '1.7', '0.3', 'small'],
       ['5.1', '3.8', '1.5', '0.3', 'small'],
       ['5.4', '3.4', '1.7', '0.2', 'small'],
       ['5.1', '3.7', '1.5', '0.4'

**Question 6**\
Find the value of second longest `petallength` of species `setosa`

In [8]:
#TODO
# read iris.csv data
iris_2d = np.genfromtxt('Data/Iris.csv', delimiter=',', dtype= None, encoding=None, 
                        skip_header=1)
# parse tuple to list
iris_2d = np.array([list(tup) for tup in iris_2d])
# get species in 4th column
setosa_spec = iris_2d[iris_2d[:, 4] == 'Iris-setosa']
# get unique petal length
unique_petal_len = np.unique(setosa_spec[:, 2])
print(unique_petal_len)
# get second longest petal length
second_longest_petallength = float(unique_petal_len[-2])
print(f'Second longest petal length: {second_longest_petallength}')

['1.0' '1.1' '1.2' '1.3' '1.4' '1.5' '1.6' '1.7' '1.9']
Second longest petal length: 1.7
