In [8]:
# 21120576 Trần Đình Nhật Trí
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import imageio

In [9]:
# Tải ảnh từ file input
image = imageio.imread('hehe.png', as_gray=True)
print(image)
print (image.shape)

[[112.937 112.937 112.937 ... 108.828 108.828 108.828]
 [112.937 112.937 112.937 ... 108.828 108.828 108.828]
 [112.937 112.937 112.937 ... 108.828 108.828 108.828]
 ...
 [ 32.358  32.358  32.358 ...  32.358  32.358  32.358]
 [ 32.358  32.358  32.358 ...  32.358  32.358  32.358]
 [ 32.358  32.358  32.358 ...  32.358  32.358  32.358]]
(648, 1152)


In [ ]:
# Thực hiện PCA
pca = PCA(n_components=20)
image_pca = pca.fit_transform(image)
print(image_pca)

In [ ]:
# Tái cấu trúc ảnh từ số thành phần chính trong PCA
image_reconstructed = pca.inverse_transform(image_pca)

# Tạo lại số chiều từ image_reconstructed để in ra màn hình
image_reconstructed = np.reshape(image_reconstructed, image.shape)


In [ ]:
# Vẽ ảnh gốc và ảnh nén màn hình
fig, axes = plt.subplots(1, 2, figsize=(8, 4))
axes[0].imshow(image, cmap='gray')
axes[0].set_title('Original Image')
axes[0].axis('off')
axes[1].imshow(image_reconstructed, cmap='gray')
axes[1].set_title('Reconstructed Image')
axes[1].axis('off')
plt.show()